name: Scrape Ruff Rules

on:
  schedule:
    - cron: '0 0 * * 0' # Run weekly on Sunday at midnight
  workflow_dispatch: # Allow manual runs

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          python-version: "3.13"

      - name: Run scraping script
        run: uv run scrape_rules.py

      - name: Commit and push if there are changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ruff_rules.csv ruff_rules.json
          git diff --staged --quiet || (git commit -m 'Update Ruff rules' && git push)
